# sqlboiler.toml
output   = "internal/models_sql_boiler"
pkgname  = "models_sql_boiler"
wipe     = true
no-tests = true

[psql]
  dbname    = "lisch"
  host      = "localhost"
  port      = 5435
  user      = "ADM"
  pass      = "2104"
  sslmode   = "disable"
  schema    = ["public"]
  blacklist = ["schema_version"]

# Aliases para tabelas
[aliases.tables.categorias]
up_singular   = "Categoria"
up_plural     = "Categorias"
down_singular = "categoria"
down_plural   = "categorias"

[aliases.tables.categoria_opcoes]
up_singular   = "CategoriaOpcao"
up_plural     = "CategoriaOpcoes"
down_singular = "categoriaOpcao"
down_plural   = "categoriaOpcoes"

[aliases.tables.culinarias]
up_singular   = "Culinaria"
up_plural     = "Culinarias"
down_singular = "culinaria"
down_plural   = "culinarias"

# Aliases para relacionamentos entre tabelas
[aliases.tables.categorias.relationships.fk_categorias_culinarias]
foreign = "Culinaria"
local   = "Categorias"

[aliases.tables.categorias.relationships.fk_categorias_tenant]
foreign = "Tenant"
local   = "Categorias"

[aliases.tables.categoria_opcoes.relationships.fk_categoria_opcoes_categorias]
foreign = "Categoria"
local   = "CategoriaOpcoes"

[aliases.tables.culinarias.relationships.categorias_id_culinaria_fkey]
foreign = "Categoria"
local   = "Culinarias"

[aliases.tables.categoria_adicionais]
up_singular   = "CategoriaAdicional"
up_plural     = "CategoriaAdicionais"
down_singular = "categoriaAdicional"
down_plural   = "categoriaAdicionais"

[aliases.tables.categoria_adicional_opcoes]
up_singular   = "CategoriaAdicionalOpcao"
up_plural     = "CategoriaAdicionalOpcoes"
down_singular = "categoriaAdicionalOpcao"
down_plural   = "categoriaAdicionalOpcoes"

# Aliases dos relacionamentos (nomes dos FKs no seu banco)
[aliases.tables.categoria_adicionais.relationships.fk_categoria_adicionais_categorias]
foreign = "Categoria"
local   = "CategoriaAdicionais"

[aliases.tables.categoria_adicional_opcoes.relationships.fk_categoria_adicional_opcoes_categoria_adicionais]
foreign = "CategoriaAdicional"
local   = "CategoriaAdicionalOpcoes"