# sqlboiler.toml
output   = "internal/models_sql_boiler"
pkgname  = "models_sql_boiler"
wipe     = true
no-tests = true

[psql]
  dbname    = "lisch"
  host      = "localhost"
  port      = 5435
  user      = "ADM"
  pass      = "2104"
  sslmode   = "disable"
  schema    = ["public"]
  blacklist = ["schema_version"]