// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_sql_boiler

var TableNames = struct {
	CategoriaAdicionais      string
	CategoriaAdicionalOpcoes string
	CategoriaOpcoes          string
	Categorias               string
	Clientes                 string
	ContasReceber            string
	Culinarias               string
	PedidoItemAdicionais     string
	PedidoItens              string
	PedidoPagamentos         string
	PedidoSeqDiaria          string
	PedidoStatus             string
	Pedidos                  string
	Products                 string
	ProdutoPrecos            string
	Produtos                 string
	Sessions                 string
	Tenants                  string
	Users                    string
}{
	CategoriaAdicionais:      "categoria_adicionais",
	CategoriaAdicionalOpcoes: "categoria_adicional_opcoes",
	CategoriaOpcoes:          "categoria_opcoes",
	Categorias:               "categorias",
	Clientes:                 "clientes",
	ContasReceber:            "contas_receber",
	Culinarias:               "culinarias",
	PedidoItemAdicionais:     "pedido_item_adicionais",
	PedidoItens:              "pedido_itens",
	PedidoPagamentos:         "pedido_pagamentos",
	PedidoSeqDiaria:          "pedido_seq_diaria",
	PedidoStatus:             "pedido_status",
	Pedidos:                  "pedidos",
	Products:                 "products",
	ProdutoPrecos:            "produto_precos",
	Produtos:                 "produtos",
	Sessions:                 "sessions",
	Tenants:                  "tenants",
	Users:                    "users",
}
