// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_sql_boiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// PedidoItemAdicionaisView is an object representing the database table.
type PedidoItemAdicionaisView struct {
	ID               null.String       `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	SeqID            null.Int64        `boil:"seq_id" json:"seq_id,omitempty" toml:"seq_id" yaml:"seq_id,omitempty"`
	IDPedidoItem     null.String       `boil:"id_pedido_item" json:"id_pedido_item,omitempty" toml:"id_pedido_item" yaml:"id_pedido_item,omitempty"`
	IDAdicionalOpcao null.String       `boil:"id_adicional_opcao" json:"id_adicional_opcao,omitempty" toml:"id_adicional_opcao" yaml:"id_adicional_opcao,omitempty"`
	Valor            types.NullDecimal `boil:"valor" json:"valor,omitempty" toml:"valor" yaml:"valor,omitempty"`
	Quantidade       null.Int          `boil:"quantidade" json:"quantidade,omitempty" toml:"quantidade" yaml:"quantidade,omitempty"`
	CreatedAt        null.Time         `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt        null.Time         `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt        null.Time         `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
}

var PedidoItemAdicionaisViewColumns = struct {
	ID               string
	SeqID            string
	IDPedidoItem     string
	IDAdicionalOpcao string
	Valor            string
	Quantidade       string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        string
}{
	ID:               "id",
	SeqID:            "seq_id",
	IDPedidoItem:     "id_pedido_item",
	IDAdicionalOpcao: "id_adicional_opcao",
	Valor:            "valor",
	Quantidade:       "quantidade",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
	DeletedAt:        "deleted_at",
}

var PedidoItemAdicionaisViewTableColumns = struct {
	ID               string
	SeqID            string
	IDPedidoItem     string
	IDAdicionalOpcao string
	Valor            string
	Quantidade       string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        string
}{
	ID:               "pedido_item_adicionais_view.id",
	SeqID:            "pedido_item_adicionais_view.seq_id",
	IDPedidoItem:     "pedido_item_adicionais_view.id_pedido_item",
	IDAdicionalOpcao: "pedido_item_adicionais_view.id_adicional_opcao",
	Valor:            "pedido_item_adicionais_view.valor",
	Quantidade:       "pedido_item_adicionais_view.quantidade",
	CreatedAt:        "pedido_item_adicionais_view.created_at",
	UpdatedAt:        "pedido_item_adicionais_view.updated_at",
	DeletedAt:        "pedido_item_adicionais_view.deleted_at",
}

// Generated where

var PedidoItemAdicionaisViewWhere = struct {
	ID               whereHelpernull_String
	SeqID            whereHelpernull_Int64
	IDPedidoItem     whereHelpernull_String
	IDAdicionalOpcao whereHelpernull_String
	Valor            whereHelpertypes_NullDecimal
	Quantidade       whereHelpernull_Int
	CreatedAt        whereHelpernull_Time
	UpdatedAt        whereHelpernull_Time
	DeletedAt        whereHelpernull_Time
}{
	ID:               whereHelpernull_String{field: "\"pedido_item_adicionais_view\".\"id\""},
	SeqID:            whereHelpernull_Int64{field: "\"pedido_item_adicionais_view\".\"seq_id\""},
	IDPedidoItem:     whereHelpernull_String{field: "\"pedido_item_adicionais_view\".\"id_pedido_item\""},
	IDAdicionalOpcao: whereHelpernull_String{field: "\"pedido_item_adicionais_view\".\"id_adicional_opcao\""},
	Valor:            whereHelpertypes_NullDecimal{field: "\"pedido_item_adicionais_view\".\"valor\""},
	Quantidade:       whereHelpernull_Int{field: "\"pedido_item_adicionais_view\".\"quantidade\""},
	CreatedAt:        whereHelpernull_Time{field: "\"pedido_item_adicionais_view\".\"created_at\""},
	UpdatedAt:        whereHelpernull_Time{field: "\"pedido_item_adicionais_view\".\"updated_at\""},
	DeletedAt:        whereHelpernull_Time{field: "\"pedido_item_adicionais_view\".\"deleted_at\""},
}

var (
	pedidoItemAdicionaisViewAllColumns            = []string{"id", "seq_id", "id_pedido_item", "id_adicional_opcao", "valor", "quantidade", "created_at", "updated_at", "deleted_at"}
	pedidoItemAdicionaisViewColumnsWithoutDefault = []string{}
	pedidoItemAdicionaisViewColumnsWithDefault    = []string{"id", "seq_id", "id_pedido_item", "id_adicional_opcao", "valor", "quantidade", "created_at", "updated_at", "deleted_at"}
	pedidoItemAdicionaisViewPrimaryKeyColumns     = []string{}
	pedidoItemAdicionaisViewGeneratedColumns      = []string{}
)

type (
	// PedidoItemAdicionaisViewSlice is an alias for a slice of pointers to PedidoItemAdicionaisView.
	// This should almost always be used instead of []PedidoItemAdicionaisView.
	PedidoItemAdicionaisViewSlice []*PedidoItemAdicionaisView
	// PedidoItemAdicionaisViewHook is the signature for custom PedidoItemAdicionaisView hook methods
	PedidoItemAdicionaisViewHook func(context.Context, boil.ContextExecutor, *PedidoItemAdicionaisView) error

	pedidoItemAdicionaisViewQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	pedidoItemAdicionaisViewType           = reflect.TypeOf(&PedidoItemAdicionaisView{})
	pedidoItemAdicionaisViewMapping        = queries.MakeStructMapping(pedidoItemAdicionaisViewType)
	pedidoItemAdicionaisViewInsertCacheMut sync.RWMutex
	pedidoItemAdicionaisViewInsertCache    = make(map[string]insertCache)
	pedidoItemAdicionaisViewUpdateCacheMut sync.RWMutex
	pedidoItemAdicionaisViewUpdateCache    = make(map[string]updateCache)
	pedidoItemAdicionaisViewUpsertCacheMut sync.RWMutex
	pedidoItemAdicionaisViewUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var pedidoItemAdicionaisViewAfterSelectMu sync.Mutex
var pedidoItemAdicionaisViewAfterSelectHooks []PedidoItemAdicionaisViewHook

var pedidoItemAdicionaisViewBeforeInsertMu sync.Mutex
var pedidoItemAdicionaisViewBeforeInsertHooks []PedidoItemAdicionaisViewHook
var pedidoItemAdicionaisViewAfterInsertMu sync.Mutex
var pedidoItemAdicionaisViewAfterInsertHooks []PedidoItemAdicionaisViewHook

var pedidoItemAdicionaisViewBeforeUpsertMu sync.Mutex
var pedidoItemAdicionaisViewBeforeUpsertHooks []PedidoItemAdicionaisViewHook
var pedidoItemAdicionaisViewAfterUpsertMu sync.Mutex
var pedidoItemAdicionaisViewAfterUpsertHooks []PedidoItemAdicionaisViewHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PedidoItemAdicionaisView) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pedidoItemAdicionaisViewAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PedidoItemAdicionaisView) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pedidoItemAdicionaisViewBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PedidoItemAdicionaisView) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pedidoItemAdicionaisViewAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PedidoItemAdicionaisView) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pedidoItemAdicionaisViewBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PedidoItemAdicionaisView) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pedidoItemAdicionaisViewAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPedidoItemAdicionaisViewHook registers your hook function for all future operations.
func AddPedidoItemAdicionaisViewHook(hookPoint boil.HookPoint, pedidoItemAdicionaisViewHook PedidoItemAdicionaisViewHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		pedidoItemAdicionaisViewAfterSelectMu.Lock()
		pedidoItemAdicionaisViewAfterSelectHooks = append(pedidoItemAdicionaisViewAfterSelectHooks, pedidoItemAdicionaisViewHook)
		pedidoItemAdicionaisViewAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		pedidoItemAdicionaisViewBeforeInsertMu.Lock()
		pedidoItemAdicionaisViewBeforeInsertHooks = append(pedidoItemAdicionaisViewBeforeInsertHooks, pedidoItemAdicionaisViewHook)
		pedidoItemAdicionaisViewBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		pedidoItemAdicionaisViewAfterInsertMu.Lock()
		pedidoItemAdicionaisViewAfterInsertHooks = append(pedidoItemAdicionaisViewAfterInsertHooks, pedidoItemAdicionaisViewHook)
		pedidoItemAdicionaisViewAfterInsertMu.Unlock()
	case boil.BeforeUpsertHook:
		pedidoItemAdicionaisViewBeforeUpsertMu.Lock()
		pedidoItemAdicionaisViewBeforeUpsertHooks = append(pedidoItemAdicionaisViewBeforeUpsertHooks, pedidoItemAdicionaisViewHook)
		pedidoItemAdicionaisViewBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		pedidoItemAdicionaisViewAfterUpsertMu.Lock()
		pedidoItemAdicionaisViewAfterUpsertHooks = append(pedidoItemAdicionaisViewAfterUpsertHooks, pedidoItemAdicionaisViewHook)
		pedidoItemAdicionaisViewAfterUpsertMu.Unlock()
	}
}

// One returns a single pedidoItemAdicionaisView record from the query.
func (q pedidoItemAdicionaisViewQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PedidoItemAdicionaisView, error) {
	o := &PedidoItemAdicionaisView{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models_sql_boiler: failed to execute a one query for pedido_item_adicionais_view")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PedidoItemAdicionaisView records from the query.
func (q pedidoItemAdicionaisViewQuery) All(ctx context.Context, exec boil.ContextExecutor) (PedidoItemAdicionaisViewSlice, error) {
	var o []*PedidoItemAdicionaisView

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models_sql_boiler: failed to assign all query results to PedidoItemAdicionaisView slice")
	}

	if len(pedidoItemAdicionaisViewAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PedidoItemAdicionaisView records in the query.
func (q pedidoItemAdicionaisViewQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models_sql_boiler: failed to count pedido_item_adicionais_view rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q pedidoItemAdicionaisViewQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models_sql_boiler: failed to check if pedido_item_adicionais_view exists")
	}

	return count > 0, nil
}

// PedidoItemAdicionaisViews retrieves all the records using an executor.
func PedidoItemAdicionaisViews(mods ...qm.QueryMod) pedidoItemAdicionaisViewQuery {
	mods = append(mods, qm.From("\"pedido_item_adicionais_view\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"pedido_item_adicionais_view\".*"})
	}

	return pedidoItemAdicionaisViewQuery{q}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PedidoItemAdicionaisView) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models_sql_boiler: no pedido_item_adicionais_view provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(pedidoItemAdicionaisViewColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	pedidoItemAdicionaisViewInsertCacheMut.RLock()
	cache, cached := pedidoItemAdicionaisViewInsertCache[key]
	pedidoItemAdicionaisViewInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			pedidoItemAdicionaisViewAllColumns,
			pedidoItemAdicionaisViewColumnsWithDefault,
			pedidoItemAdicionaisViewColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(pedidoItemAdicionaisViewType, pedidoItemAdicionaisViewMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(pedidoItemAdicionaisViewType, pedidoItemAdicionaisViewMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"pedido_item_adicionais_view\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"pedido_item_adicionais_view\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models_sql_boiler: unable to insert into pedido_item_adicionais_view")
	}

	if !cached {
		pedidoItemAdicionaisViewInsertCacheMut.Lock()
		pedidoItemAdicionaisViewInsertCache[key] = cache
		pedidoItemAdicionaisViewInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PedidoItemAdicionaisView) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models_sql_boiler: no pedido_item_adicionais_view provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(pedidoItemAdicionaisViewColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	pedidoItemAdicionaisViewUpsertCacheMut.RLock()
	cache, cached := pedidoItemAdicionaisViewUpsertCache[key]
	pedidoItemAdicionaisViewUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			pedidoItemAdicionaisViewAllColumns,
			pedidoItemAdicionaisViewColumnsWithDefault,
			pedidoItemAdicionaisViewColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			pedidoItemAdicionaisViewAllColumns,
			pedidoItemAdicionaisViewPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models_sql_boiler: unable to upsert pedido_item_adicionais_view, could not build update column list")
		}

		ret := strmangle.SetComplement(pedidoItemAdicionaisViewAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(pedidoItemAdicionaisViewPrimaryKeyColumns) == 0 {
				return errors.New("models_sql_boiler: unable to upsert pedido_item_adicionais_view, could not build conflict column list")
			}

			conflict = make([]string, len(pedidoItemAdicionaisViewPrimaryKeyColumns))
			copy(conflict, pedidoItemAdicionaisViewPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"pedido_item_adicionais_view\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(pedidoItemAdicionaisViewType, pedidoItemAdicionaisViewMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(pedidoItemAdicionaisViewType, pedidoItemAdicionaisViewMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models_sql_boiler: unable to upsert pedido_item_adicionais_view")
	}

	if !cached {
		pedidoItemAdicionaisViewUpsertCacheMut.Lock()
		pedidoItemAdicionaisViewUpsertCache[key] = cache
		pedidoItemAdicionaisViewUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
